<a href="https://colab.research.google.com/github/salim-hbk/ai-ml/blob/main/Gradient_Tape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import tensorflow as tf
import numpy as np

In [7]:
ex_1 = np.arange(1, 9)
constant_1 = tf.constant(ex_1, shape=(8,))
constant_1

<tf.Tensor: shape=(8,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8])>

In [10]:
ex_1 = np.arange(1, 9)
square_1 = tf.square(ex_1)
square_2 = tf.square(2)
square_1, square_2

(<tf.Tensor: shape=(8,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [14]:
constant_1_2x4 =tf.reshape(constant_1, shape=(2,4))
constant_1_2x4

<tf.Tensor: shape=(2, 4), dtype=int64, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

In [24]:
mat_a = np.arange(1,9)
mat_b = np.arange(11, 19)
tensor_1 = tf.Variable(mat_a, shape=(8))
tensor_2 = tf.Variable(mat_b, shape=(8))
result = tensor_1 + tensor_2
result

<tf.Tensor: shape=(8,), dtype=int64, numpy=array([12, 14, 16, 18, 20, 22, 24, 26])>

In [29]:
x  = tf.constant(2.0, shape=(1))
with tf.GradientTape() as t:
  t.watch(x)
  y = 3*x**3 - 2*x**2 + x
  z = tf.reduce_sum(y)

dz_dx = t.gradient(z, x)
dz_dx

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([29.], dtype=float32)>

In [30]:
(9* (2**2)) - (4*2) +2

30

In [32]:
36-8

28